apiVersion: v1
kind: Service
metadata:
  name: testingsite 
  labels:
    app: website
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP 
    port: 80
    targetPort: 80
  selector:
    app: website
